export const instruments = [
  { name: "Bass Trombo", channel: 0 },
  { name: "Horn Solo", channel: 1 },
  { name: "Horns Stacc", channel: 2 },
  { name: "Horns Susta", channel: 3 },
  { name: "Tenor Tromb", channel: 4 },
  { name: "Trombones S", channel: 5 },
  { name: "Trombones S", channel: 6 },
  { name: "Trumpet Sol", channel: 7 },
  { name: "Trumpets St", channel: 8 },
  { name: "Trumpets Su", channel: 9 },
  { name: "Tuba Stacca", channel: 10 },
  { name: "Tuba Sustai", channel: 11 },
  { name: "Female", channel: 12 },
  { name: "Male", channel: 13 },
  { name: "Mixed", channel: 14 },
  { name: "Harp", channel: 15 },
  { name: "Grand Piano", channel: 16 },
  { name: "All Pe", channel: 17 },
  { name: "Bass D", channel: 18 },
  { name: "Chimes", channel: 19 },
  { name: "Conga", channel: 20 },
  { name: "Cymbal", channel: 21 },
  { name: "Glocke", channel: 22 },
  { name: "Timpan", channel: 23 },
  { name: "Triang", channel: 24 },
  { name: "Variou", channel: 25 },
  { name: "Xyloph", channel: 26 },
  { name: "1st Violi", channel: 27 },
  { name: "1st Violi", channel: 28 },
  { name: "1st Violi", channel: 29 },
  { name: "2nd Violi", channel: 30 },
  { name: "2nd Violi", channel: 31 },
  { name: "2nd Violi", channel: 32 },
  { name: "Basses Pi", channel: 33 },
  { name: "Basses St", channel: 34 },
  { name: "Basses Su", channel: 35 },
  { name: "Celli Piz", channel: 36 },
  { name: "Celli Sta", channel: 37 },
  { name: "Celli Sus", channel: 38 },
  { name: "Cello Sol", channel: 39 },
  { name: "Violas Pi", channel: 40 },
  { name: "Violas Su", channel: 41 },
  { name: "Violin So", channel: 42 },
  { name: "Alto Fl", channel: 43 },
  { name: "Bass Cl", channel: 44 },
  { name: "Bassoon", channel: 45 },
  { name: "Bassoon", channel: 46 },
  { name: "Clarine", channel: 47 },
  { name: "Clarine", channel: 48 },
  { name: "Contrab", channel: 49 },
  { name: "Cor Ang", channel: 50 },
  { name: "Flute S", channel: 51 },
  { name: "Flutes", channel: 52 },
  { name: "Flutes", channel: 53 },
  { name: "Oboe So", channel: 54 },
  { name: "Oboes S", channel: 55 },
  { name: "Piccolo", channel: 56 },
];
